# Generated by Django 2.2.1 on 2019-06-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(max_length=64)),
                ('dropped_out', models.BooleanField()),
            ],
        ),
    ]
